### ISSUE TITLE
About you're repo's license

### ISSUE THREAD

**Issue by mj-ehsan** [AlucardDH/dh-reshade-shaders#2]
Hi. I'm a reshade shader developer and I'm interested in your shaders, specifically dh-rtgi. But unfortunately, it seems like you left them and are not working on them anymore. As there's no license included with your repo/codes (which ofc means all rights reserved), I wonder if you let me continue the development of these shaders and update them. Please answer to my email: "MJ.Ehsan1999.2nd@Gmail.com". Thanks.

**Comment by AlucardDH** [comment]
I added a licence to the repo (GNU2) so you can reuse the code.

Concerning dh_rtgi, I'm still working on it but still did not push an updated version.

**Comment by mj-ehsan** [comment]
Thanks for the reply. Great. I'm waiting for your future updates.
