### ISSUE TITLE
dh_uber_rt - slightly different colors rendered in "performance mode"

### ISSUE THREAD

**Issue by gabriele2000** [AlucardDH/dh-reshade-shaders#5]
If I put ReShade in "performance mode" the shader should behave like I set it, without visible differences as far as I know, while consuming less frametime thus boosting the performance.

What I get, for example in Battlefield 3, in performance mode, is slightly different colors bouncing off things.
In this case, the orange of an UI element gets translated into a kinda-purple.

I'll drop my ReShade.ini file and the preset file.

[preset.txt](https://github.com/AlucardDH/dh-reshade-shaders/files/11995723/preset.txt)
[ReShade.txt](https://github.com/AlucardDH/dh-reshade-shaders/files/11995725/ReShade.txt)

**Comment by AlucardDH** [comment]
Battlefield 3 is a DirectX11 game.

Does this problem occurs on other games and/or other API ? 

I tested my shader on multiple games but never tried the performance mode (I never saw any improvement while active).
I'll try to reproduce and eventually fix it.

**Comment by gabriele2000** [comment]
> Does this problem occurs on other games and/or other API ?

So far, Battlefield 3 is the only game where I've noticed this thing... I'm using your shader since just a month, I come from Marty's RTGI and since now yours is more viable for my needs (basically a RT shader that doesn't tank my performance while giving me very little), I've liked it so much that I now use this shader.
By the way, thanks a lot for fixing DX9 compiling along the last update!
I could finally continue to play "Minecraft: Story Mode" since I wanted to play it with RTGI!

> I tested my shader on multiple games but never tried the performance mode (I never saw any improvement while active). I'll try to reproduce and eventually fix it.

Trust me, the difference of those 0.4/0.8ms less is a lot.

**Comment by AlucardDH** [comment]
0.4/0.8ms less is a lot, right :)
I reinstalling BF3 right now.

**Comment by gabriele2000** [comment]
> 0.4/0.8ms less is a lot, right :) I reinstalling BF3 right now.

I believe there's a math error somewhere... I installed Homefront: The Revolution since I've never played it before and I immediately noticed the problem.

It seems that the orange is being translated, in performance mode, to that weird purple
![normal](https://github.com/AlucardDH/dh-reshade-shaders/assets/12186181/3b885faf-5583-465c-b32d-c075f373d8a6)
![performance](https://github.com/AlucardDH/dh-reshade-shaders/assets/12186181/ae396575-f28e-4ee9-b5d6-65af96c123a7)

**Comment by gabriele2000** [comment]
@AlucardDH did you happen to find something?
The issue occur in 0.12 too.

I thought that the resolution scale was the problem, but I verified and it isn't.

**Comment by gabriele2000** [comment]
0.14 fixed it... either this or ReShade 5.9 that dropped yesterday!

By the way, nice new update!
For performance stuff, I use 0.25 resolution scale and no noise thing, I use both parameters at 1, you know what I mean?
It's even more wonderful now!
