### ISSUE TITLE
dh_uber_rt 0.13.0 compile crash on DX9

### ISSUE THREAD

**Issue by Clippy95** [AlucardDH/dh-reshade-shaders#6]
![image](https://github.com/AlucardDH/dh-reshade-shaders/assets/7094610/a4035a7a-0f66-43d7-b09e-0896f3e32ac1)

**Comment by AlucardDH** [comment]
It was also reported on my Discord server. 
I just push a fix : 
https://github.com/AlucardDH/dh-reshade-shaders/commit/06b8bf5decf78338393eb54112d48ab3bfa993e0

Could you please test it again ?

**Comment by Clippy95** [comment]
> It was also reported on my Discord server. I just push a fix : [06b8bf5](https://github.com/AlucardDH/dh-reshade-shaders/commit/06b8bf5decf78338393eb54112d48ab3bfa993e0)
> 
> Could you please test it again ?

It works now, big thanks!
